-- CreateTable
CREATE TABLE "Reports" (
    "reportId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "propertyId" STRING NOT NULL,
    "reportNickName" STRING,
    "creation_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified" TIMESTAMP(3) NOT NULL,
    "website" STRING,
    "address" STRING,
    "city" STRING,
    "state" STRING,
    "zip" STRING,
    "image" STRING,
    "interest" FLOAT8,
    "closing_cost" FLOAT8,
    "exit_cap" FLOAT8,
    "loan_to_value" FLOAT8,
    "year_one_cap" FLOAT8,
    "unlevered_irr" FLOAT8,
    "levered_irr" FLOAT8,
    "unlevered_mom" FLOAT8,
    "levered_mom" FLOAT8,
    "levered_profit" FLOAT8,
    "bedrooms" INT4,
    "bathrooms" INT4,
    "year_built" INT4,
    "water_source" STRING,
    "property_subtype" STRING,
    "listing_price" FLOAT8,
    "sales_status" STRING,
    "sqft" INT4,
    "all_cash_on_cash" JSONB,
    "all_insurance" JSONB,
    "all_water" JSONB,
    "all_electricity" JSONB,
    "all_RM" JSONB,
    "all_vacancy" JSONB,
    "all_revenue" JSONB,
    "all_management" JSONB,
    "all_HOA" JSONB,
    "all_utilities" JSONB,
    "all_gas" JSONB,
    "all_capex" JSONB,
    "all_total_expenses" JSONB,
    "all_total_loan_payment" JSONB,
    "all_principal" JSONB,
    "all_interest" JSONB,
    "all_loan_balance" JSONB,
    "all_balloon" JSONB,
    "all_ending_balance" JSONB,
    "all_NOI" JSONB,
    "all_NOI_margin" JSONB,
    "all_net_deposit_proceeds" JSONB,
    "all_unlevered_yield" JSONB,
    "all_DSCR" JSONB,
    "all_debt_yield" JSONB,
    "all_NOI_growth" JSONB,
    "all_CFG_growth" JSONB,

    CONSTRAINT "Reports_pkey" PRIMARY KEY ("reportId")
);

-- CreateTable
CREATE TABLE "UserTokens" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "token" STRING NOT NULL,
    "creation_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_modified" TIMESTAMP(3) NOT NULL,
    "time_to_live" INT4 NOT NULL,

    CONSTRAINT "UserTokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" STRING NOT NULL,
    "email" STRING NOT NULL,
    "privateKey" STRING NOT NULL,
    "uniqueToken" STRING NOT NULL,
    "password" STRING NOT NULL,
    "creation_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Reports_reportId_key" ON "Reports"("reportId");

-- CreateIndex
CREATE UNIQUE INDEX "UserTokens_id_key" ON "UserTokens"("id");

-- CreateIndex
CREATE UNIQUE INDEX "UserTokens_userId_key" ON "UserTokens"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Users_id_key" ON "Users"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Users_username_key" ON "Users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "Users_email_key" ON "Users"("email");
